[program:algo-trading]
directory=/home/ubuntu/algo-trading/backend
command=/home/ubuntu/algo-trading/backend/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1
user=ubuntu
autostart=true
autorestart=true
stderr_logfile=/var/log/algo-trading/error.log
stdout_logfile=/var/log/algo-trading/output.log
environment=PATH="/home/ubuntu/algo-trading/backend/venv/bin"
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10